# Generated by Django 4.2.11 on 2024-12-06 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='U1A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(error_messages={'required': 'error.required'}, max_length=255, verbose_name='Navn på udfylder')),
                ('revisionsfirma', models.CharField(max_length=255, verbose_name='Revisionsfirma')),
                ('virksomhedsnavn', models.CharField(error_messages={'required': 'error.required'}, max_length=255, verbose_name='Virksomhedsnavn')),
                ('cvr', models.CharField(error_messages={'invalid': 'error.invalid_cvr', 'required': 'error.required'}, max_length=255, verbose_name='CVR')),
                ('email', models.CharField(error_messages={'invalid': 'error.invalid_email', 'required': 'error.required'}, max_length=255, verbose_name='Email-adresse')),
                ('regnskabsår', models.IntegerField(choices=[(2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019')], verbose_name='Udbyttet vedrører regnskabsåret')),
                ('u1_udfyldt', models.BooleanField(blank=True, choices=[(None, '---------'), ('0', 'No'), ('1', 'Yes')], null=True, verbose_name='Har du allerede udfyldt U1?')),
                ('udbytte', models.DecimalField(decimal_places=2, error_messages={'invalid': 'error.number_required', 'required': 'error.required'}, max_digits=12, verbose_name='Udbetalt/godskrevet udbytte i DKK, før skat')),
                ('noter', models.TextField(blank=True, null=True, verbose_name='Særlige oplysninger')),
                ('by', models.CharField(error_messages={'required': 'error.required'}, max_length=255, verbose_name='By')),
                ('dato', models.DateField(error_messages={'invalid': 'error.invalid_date', 'required': 'error.required'}, verbose_name='Dato')),
                ('underskriftsberettiget', models.CharField(error_messages={'required': 'error.required'}, max_length=255, verbose_name='Navn på underskriftsberettiget for selskabet')),
                ('oprettet', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('oprettet_af_cpr', models.CharField(db_index=True, error_messages={'required': 'error.required'}, verbose_name='Oprettet af CPR')),
                ('oprettet_af_cvr', models.CharField(blank=True, db_index=True, null=True, verbose_name='Oprettet af CVR')),
            ],
        ),
        migrations.CreateModel(
            name='U1AItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr_cvr_tin', models.CharField(error_messages={'invalid': 'error.invalid_cpr_cvr', 'required': 'error.required'}, validators=[django.core.validators.RegexValidator('^\\d{8}(\\d{2})?$', 'error.invalid_cpr_cvr')], verbose_name='CPR-nr / CVR-nr / TIN')),
                ('navn', models.CharField(error_messages={'required': 'error.required'}, verbose_name='Navn')),
                ('adresse', models.CharField(error_messages={'required': 'error.required'}, verbose_name='Adresse')),
                ('postnummer', models.CharField(error_messages={'required': 'error.required'}, verbose_name='Postnummer')),
                ('by', models.CharField(error_messages={'required': 'error.required'}, verbose_name='By')),
                ('land', models.CharField(error_messages={'required': 'error.required'}, verbose_name='Land')),
                ('udbytte', models.DecimalField(decimal_places=2, error_messages={'invalid': 'error.number_required', 'required': 'error.required'}, max_digits=12, verbose_name='Udbetalt/godskrevet udbytte i DKK, før skat')),
                ('oprettet', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('u1a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u1a', to='udbytte.u1a')),
            ],
        ),
    ]
