# Generated by Django 4.2.11 on 2024-12-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udbytte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u1aitem',
            name='u1a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udbytte.u1a'),
        ),
    ]
