# Generated by Django 4.2.11 on 2025-01-16 08:36

from django.db import migrations, models
import udbytte.models


class Migration(migrations.Migration):

    dependencies = [
        ('udbytte', '0002_alter_u1aitem_u1a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u1a',
            name='regnskabsår',
            field=models.IntegerField(validators=[udbytte.models.validate_year], verbose_name='Udbyttet vedrører regnskabsåret'),
        ),
    ]
