# Generated by Django 4.2.11 on 2025-03-04 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udbytte', '0003_alter_u1a_regnskabsår'),
    ]

    operations = [
        migrations.AddField(
            model_name='u1a',
            name='dato_udbetaling',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), error_messages={'invalid': 'error.invalid_date', 'required': 'error.required'}, verbose_name='Udbetalings dato'),
            preserve_default=False,
        ),
    ]
