# Generated by Django 4.2.11 on 2025-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udbytte', '0005_remove_u1a_dato_udbetaling_u1a_dato_vedtagelse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u1a',
            name='u1_udfyldt',
            field=models.BooleanField(blank=True, null=True, verbose_name='Har du allerede udfyldt U1?'),
        ),
    ]
