# Generated by Django 3.2.13 on 2023-06-23 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligatorisk_pension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligatoriskpension',
            name='beløb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
