stages:
  - test

linting:
  stage: test
  image: python:3.6
  before_script:
    - apt update
    - apt install -y libxmlsec1-dev
    - pip3 install flake8==3.8.1
    - pip3 install -r backend/requirements.txt
  script:
    - flake8 --ignore E501,E226 backend/
