#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`;
if [[ $BRANCH != 'master' ]]; then
echo "Can only deploy master branch to prod";
exit 1;
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "${DIR}/ansible"
ansible-playbook -i akapprod01, -K playbooks/production.yml --ask-vault-pass
popd
