services:
  selvbetjening-db:
    container_name: selvbetjening-db
    image: postgres:13

    network_mode: "host"
    env_file:
      - ./dev-environment/selvbetjening.env
    volumes:
      - selvbetjening-postgres-data:/var/lib/postgresql/data

  selvbetjening-web:
    container_name: selvbetjening-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - selvbetjening-db
    network_mode: "host"
    env_file:
      - ./dev-environment/selvbetjening.env
    environment:
      - TEST=true
      - MAKE_MIGRATIONS=true
      - RUN_MIGRATIONS=true
    volumes:
      - ./log:/log:rw
      - ./dev-environment/cert:/ssl:ro
      - ./upload:/upload  # Matcher MEDIA_ROOT i django settings
      - ./akap/mypy.ini:/mypy.ini:ro
    command: gunicorn -b 0.0.0.0:8000 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output # reload on code changes

  selvbetjening-cron:
    container_name: selvbetjening-cron
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: [ ]
    environment:
      - MAKE_MIGRATIONS=false
      - RUN_MIGRATIONS=false
    volumes:
      - ./akap/:/app
      - ./logs:/var/log/aka
    depends_on:
      - selvbetjening-db
    command: [ "supercronic", "/crontab" ]


  selvbetjening-test-idp:
    container_name: selvbetjening-test-idp
    user: "1000:1000"
    image: kenchan0130/simplesamlphp
    network_mode: "host"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:8000/saml/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:8000/login/callback/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:8000/logout/callback/
      SIMPLESAMLPHP_IDP_CERTIFICATE: /var/www/simplesamlphp/cert/selfsigned.crt
      SIMPLESAMLPHP_IDP_PRIVATEKEY: /var/www/simplesamlphp/cert/selfsigned.key

    volumes:
      - ./dev-environment/cert/idp/selfsigned.crt:/var/www/simplesamlphp/cert/server.crt:ro
      - ./dev-environment/cert/idp/selfsigned.key:/var/www/simplesamlphp/cert/server.pem:ro
      - ./dev-idp/authsources.php:/var/www/simplesamlphp/config/authsources.php:ro
      - ./dev-idp/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php:ro

  selvbetjening-mailhog:
    container_name: selvbetjening-mailhog
    image: mailhog/mailhog
    network_mode: "host"
    # UI will be available at http://localhost:8025
    hostname: mailhog
    # environment config doc: https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
    logging:
      # Disabled because it spams the log. Remove this to get mailhog logs.
      driver: none

volumes:
  selvbetjening-postgres-data:
