services:

  akap-db:
    container_name: akap-db
    image: postgres:13
    env_file:
      - ./dev-environment/akap.env
    volumes:
      - akap-postgres-data:/var/lib/postgresql/data
    networks:
      - database

  akap-web:
    container_name: akap-web
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - akap-db
    env_file:
      - ./dev-environment/akap.env
    ports:
      - "8010:8010"
    environment:
      - TEST=true
      - MAKE_MIGRATIONS=true
      - RUN_MIGRATIONS=true
    volumes:
      - ./log:/log:rw
      - ./dev-environment/cert:/ssl:ro
      - ./upload:/upload  # Matcher MEDIA_ROOT i django settings
      - ./akap/mypy.ini:/mypy.ini:ro
    command: gunicorn -b 0.0.0.0:8010 project.wsgi:application --reload -w 1 --access-logfile - --error-logfile - --capture-output   # reload on code changes
    networks:
      - default
      - database

  akap-cron:
    container_name: akap-cron
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: [ ]
    environment:
      - MAKE_MIGRATIONS=false
      - RUN_MIGRATIONS=false
    volumes:
      - ./akap/:/app
      - ./logs:/var/log/aka
    depends_on:
      - akap-db
    command: [ "supercronic", "/crontab" ]
    networks:
      - database

  akap-idp:
    container_name: akap-idp
    user: "1000:1000"
    image: kenchan0130/simplesamlphp
    ports:
      - "8011:8011"
    environment:
      HTTP_PORT: 8011
      SIMPLESAMLPHP_SP_ENTITY_ID: http://akap-web:8010/saml/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://akap-web:8010/login/callback/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://akap-web:8010/logout/callback/
      SIMPLESAMLPHP_IDP_CERTIFICATE: /var/www/simplesamlphp/cert/selfsigned.crt
      SIMPLESAMLPHP_IDP_PRIVATEKEY: /var/www/simplesamlphp/cert/selfsigned.key

    volumes:
      - ./dev-environment/dev-idp/ports.conf:/etc/apache2/ports.conf:ro
      - ./dev-environment/dev-idp/site.conf:/etc/apache2/sites-available/simplesamlphp.conf:ro
      - ./dev-environment/cert/idp/selfsigned.crt:/var/www/simplesamlphp/cert/server.crt:ro
      - ./dev-environment/cert/idp/selfsigned.key:/var/www/simplesamlphp/cert/server.pem:ro
      - ./dev-environment/dev-idp/authsources.php:/var/www/simplesamlphp/config/authsources.php:ro
      - ./dev-environment/dev-idp/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php:ro
    networks:
      - default

  akap-mailhog:
    container_name: akap-mailhog
    image: mailhog/mailhog
    ports:
      - "8012:8025"
    # UI will be available at http://localhost:8012
    hostname: mailhog
    # environment config doc: https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md
    networks:
      - default

  akap-hosts-updater:
    container_name: akap-hosts-updater
    image: bash
    volumes:
      - ./dev-environment/hosts.sh:/hosts.sh:ro
      - /etc/hosts:/hosts:rw
    command: [ "bash", "/hosts.sh" ]

volumes:
  akap-postgres-data:

networks:
  default:
  database:
