#!/bin/bash

# This script is used to generate a Javascript Object variable
# from a Json file.
# The Json file should be placed in the shared/ folder
#
# Arguments: $1 is the path to the Json file
#            $2 is the name of the variable

printf "/*****************************************************************************************\n"
printf " * IMPORTANT\n"
printf " * DO NOT EDIT THIS FILE\n"
printf " * IT IS AUTO GENERATED FROM $1\n"
printf " * And will be overwritten by makefile\n"
printf " * \n"
printf " * It is generated by the script $0 \n"
printf " *****************************************************************************************/\n"
printf "let $2 = "
cat $1 | sed 's/"\([^"]*\)" *:/\1:/g'
printf "\nexport {$2};\n"
