# Generated by Django 3.2.13 on 2023-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligatorisk_pension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligatoriskpension',
            name='beløb',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
