<template>

  <article>

    <h1>{{ $t('loentraek.titel2') }}</h1>

    <form>
    <fieldset>
      <input type="submit" :value="$t('common.gem')" @click="isSubmitted = true">
      <button > {{ $t('loentraek.indlaes_fra_fil') }} </button>
      <button @click.prevent="navigateTo('/loentraeksindberetning')"> {{ $t('common.tilbage') }} </button>
      <button > {{ $t('loentraek.indlaes_fra_forrige_redegoerelse') }} </button>
    </fieldset>

      <table id="loentraeksberegninger">
        <tbody>
          <tr>
            <td></td>
            <td> {{ $t('loentraek.fordeling') }}</td>
            <td> {{ $t('loentraek.fordelt') }}</td>
            <td> {{ $t('loentraek.difference') }}</td>
          </tr>
          <tr>
            <td> {{ $t('loentraek.loentraek') }}</td>
            <td> <input type="number" :value="fordeling" disabled></td>
            <td> <input type="number" :value="fordeling" disabled></td>
            <td> <input type="number" :value="fordeling" disabled></td>
          </tr>
        </tbody>
      </table>

    <table>
      <thead>
      <tr>
        <th>{{ $t('common.cpr_nr') }}</th>
        <th>{{ $t('loentraek.aftalenr') }}</th>
        <th>{{ $t('loentraek.loentraek') }}</th>
        <th>{{ $t('loentraek.nettoloen') }}</th>
        <!--<th></th>-->
      </tr>
      </thead>
      <tbody>
      <!--TODO: Is all fields in a row required?-->
      <tr v-for="(aftale, index) in aftaler" :key="index" @keyup.once="addNewRow">
        <td><input type="text" v-model="aftale.cpr" :minlength="10"
                   :maxlength="10"></td>
        <td><input type="text" v-model="aftale.aftalenr"></td>
        <td><input type="text" v-model="aftale.loentraek"
                   v-bind:required="cprIsFilled(index)"></td>
        <td><input type="text" v-model="aftale.nettoloen"
                   v-bind:required="cprIsFilled(index)"></td>
        <!--<td><a @click="deleteFile(index)">{{ $t('inkasso.slet') }}</a></td>-->
      </tr>
      </tbody>
    </table>
    </form>
  </article>

</template>

<script>
// The file fordringsgruppe.js below is generated by the command `make frontend`
// import { notify } from '../utils/notify/Notifier.js'

export default {
  data: function () {
    return {
      fordeling: 0,
      fordelt: 0,
      difference: 0,
      aftaler: [
        {
          cpr: '',
          aftalenr: '',
          loentraek: '',
          nettoloen: ''
        }
      ]
    }
  },
  computed: {

  },
  methods: {
    navigateTo: function (nav) {
      this.$router.push({
        path: nav
      })
    },
    addNewRow: function () {
      this.aftaler.push({
        cpr: '',
        aftalenr: '',
        loentraek: '',
        nettoloen: ''
      })
    },
    cprIsFilled: function (index) {
      return (this.aftaler[index].cpr !== '')
    },
    getCSRFToken: function () {
      this.csrftoken = document.cookie.replace(
        /(?:(?:^|.*;\s*)csrftoken\s*=\s*([^;]*).*$)|^.*$/,
        '$1'
      )
    }
  },
  created: function () {
    this.getCSRFToken()
  }
}
</script>

<style scoped>
/*table {*/
  /*padding: 1.875rem;*/
/*}*/
</style>
