<template>

  <article>

    <h1>{{ $t('loentraek.titel2') }}</h1>
    <fieldset>
      <input type="submit" :value="$t('common.gem')" @click="isSubmitted = true">
      <button > {{ $t('loentraek.indlaes_fra_fil') }} </button>
      <button > {{ $t('common.tilbage') }} </button>
      <button > {{ $t('loentraek.indlaes_fra_forrige_redegoerelse') }} </button>
    </fieldset>

    <table>
      <thead>
      <tr>
        <th>{{ $t('common.cpr_nr') }}</th>
        <th>{{ $t('loentraek.aftalenr') }}</th>
        <th>{{ $t('loentraek.loentraek') }}</th>
        <th>{{ $t('loentraek.nettoloen') }}</th>
        <!--<th></th>-->
      </tr>
      </thead>
      <tbody>
      <tr v-for="(aftale, index) in aftaler" :key="index" @keyup.once="addNewRow">
        <td><input type="text" v-model="aftale.cpr" :minlength="10" :maxlength="10"></td>
        <td><input type="text" v-model="aftale.aftalenr"></td>
        <td><input type="text" v-model="aftale.loentraek"></td>
        <td><input type="text" v-model="aftale.nettoloen"></td>
        <!--<td><a @click="deleteFile(index)">{{ $t('inkasso.slet') }}</a></td>-->
      </tr>
      </tbody>
    </table>
  </article>

</template>

<script>
// The file fordringsgruppe.js below is generated by the command `make frontend`
// import { notify } from '../utils/notify/Notifier.js'

export default {
  data: function () {
    return {
      aftaler: [
        {
          cpr: '',
          aftalenr: '',
          loentraek: '',
          nettoloen: ''
        }
      ]
    }
  },
  computed: {

  },
  methods: {
    addNewRow: function () {
      this.aftaler.push({
        cpr: '',
        aftalenr: '',
        loentraek: '',
        nettoloen: ''
      })
    },
    getCSRFToken: function () {
      this.csrftoken = document.cookie.replace(
        /(?:(?:^|.*;\s*)csrftoken\s*=\s*([^;]*).*$)|^.*$/,
        '$1'
      )
    }
  },
  created: function () {
    this.getCSRFToken()
  }
}
</script>

<style scoped>

</style>
