<template>

    <article>
        <form @submit.prevent="sendFormRequest()">

        <h1>{{ $t("loentraek.titel1") }}</h1>

          <div class="container-fluid">
            <div class="row">
              <div class="col-4">
                <s-field name="ger_nr"
                         :label="$t('attributes.ger_nr')"
                         type="text"
                         :validate="{required: true, digits: 8}"
                         v-model="ger_nr"/>
              </div>
            </div>
            <div class="row">
              <div class="col-3">
                <!--TODO: Change to https://www.npmjs.com/package/vue-monthly-picker or https://github.com/charliekassel/vuejs-datepicker-->
                <s-field name="traekmaaned"
                         :label="$t('attributes.traekmaaned')"
                         type="month"
                         :validate="{required: true}"
                         v-model="traekmaaned"
                />
              </div>
            </div>
            <div class="row">
              <div class="col-4">
                <s-field name="loentraek"
                         :label="$t('attributes.loentraek')"
                         type="text"
                         :validate="{required: true}"
                         v-model="loentraek"
                />
              </div>
            </div>
          </div>

            <div class="row">
              <div class="col">
                <button @click.prevent="navigateTo('/loentraeksindberetning/indberet_pr_cpr')">
                  {{ $t('loentraek.fordel_pr_cpr') }}
                </button>
                <button type="submit"
                        @click="isSubmitted = true">
                  {{ $t('common.indberet') }}
                </button>
              </div>
            </div>

        </form>

    </article>

</template>

<script>
import axios from 'axios'
import formValid from '@/mixins/formValid'
// The file fordringsgruppe.js below is generated by the command `make frontend`
import { notify } from '../utils/notify/Notifier.js'

export default {
  mixins: [formValid],
  data: function () {
    return {
      ger_nr: null,
      traekmaaned: null,
      loentraek: null,
      csrftoken: null,
      isSubmitted: false
    }
  },
  computed: {

  },
  methods: {
    navigateTo: function (nav) {
      this.$router.push({
        path: nav
      })
    },
    getCSRFToken: function () {
      this.csrftoken = document.cookie.replace(
        /(?:(?:^|.*;\s*)csrftoken\s*=\s*([^;]*).*$)|^.*$/,
        '$1'
      )
    },
    getFileData: function (files) {
      this.fil = files[0]
    },
    sendFormRequest: function () {
      if (!this.formValid) {
        this.$validator.validateAll()
        return
      }
      let formdata = new FormData()
      formdata.append(this.ger_nr)
      formdata.append(this.traekmaaned)
      formdata.append(this.loentraek)
      axios({
        url: '/inkassosag',
        data: formdata,
        method: 'post',
        headers: {
          'X-CSRFToken': this.csrftoken,
          'X-AKA-BRUGER': 'Unknown'
        }
      })
        .then(res => {
          notify('The server has responded and it was happy!')
          console.log('Server response!')
          console.log(res)
        })
        .catch(err => {
          console.log('there was an error')
          console.log(err.message)
        })
    }
  },
  created: function () {
    this.getCSRFToken()
    notify(`Welcome to this page. ${this.$t('title')}`)
  }
}
</script>

<style scoped>

</style>
