<template>

    <article>

        <h1>{{ $t("loentraek.titel1") }}</h1>

        <form @submit.prevent="sendFormRequest()">

            <fieldset>
                <label id="lbl_ger_nr" for="ger_nr">{{ $t("loentraek.ger_nr") }}</label>
                <input id="ger_nr" type="text" v-model="ger_nr" required>
            </fieldset>

            <fieldset>
                <label id="lbl_traekmaaned" for="traekmaaned">{{ $t("loentraek.traekmaaned") }}</label>
                <input id="traekmaaned" type="month" v-model="traekmaaned" required>
            </fieldset>

            <fieldset>
                <label id="lbl_loentraek" for="loentraek">{{ $t("loentraek.loentraek") }}</label>
                <input id="loentraek" type="text" v-model="loentraek" required>
            </fieldset>

            <fieldset>
                <button @click.prevent="navigateTo('/loentraeksindberetning/indberet_pr_cpr')"> {{ $t('loentraek.fordel_pr_cpr') }} </button>
                <input type="submit" :value="$t('common.indberet')" @click="isSubmitted = true">
            </fieldset>

        </form>

    </article>

</template>

<script>
import axios from 'axios'
// The file fordringsgruppe.js below is generated by the command `make frontend`
import { notify } from '../utils/notify/Notifier.js'

export default {
  data: function () {
    return {
      ger_nr: null,
      traekmaaned: null,
      loentraek: null,
      csrftoken: null,
      isSubmitted: false
    }
  },
  computed: {

  },
  methods: {
    navigateTo: function (nav) {
      this.$router.push({
        path: nav
      })
    },
    getCSRFToken: function () {
      this.csrftoken = document.cookie.replace(
        /(?:(?:^|.*;\s*)csrftoken\s*=\s*([^;]*).*$)|^.*$/,
        '$1'
      )
    },
    getFileData: function (files) {
      this.fil = files[0]
    },
    // fetchFormData: function () {
    //   let formdata = new FormData()
    //   let that = this
    //   function appendData (string) {
    //     if (that[string] !== null) {
    //       formdata.append(string, that[string])
    //     }
    //   }
    //   this.form_fields.forEach(appendData)
    //   return formdata
    // },
    sendFormRequest: function () {
      // let formdata = this.fetchFormData()
      let formdata = new FormData()
      formdata.append(this.ger_nr)
      formdata.append(this.traekmaaned)
      formdata.append(this.loentraek)
      axios({
        url: '/inkassosag',
        data: formdata,
        method: 'post',
        headers: {
          'X-CSRFToken': this.csrftoken,
          'X-AKA-BRUGER': 'Unknown'
        }
      })
        .then(res => {
          notify('The server has responded and it was happy!')
          console.log('Server response!')
          console.log(res)
        })
        .catch(err => {
          console.log('there was an error')
          console.log(err.message)
        })
    }
  },
  created: function () {
    this.getCSRFToken()
    notify(`Welcome to this page. ${this.$t('title')}`)
  }
}
</script>

<style scoped>

</style>
