<template>

    <article>
        <form @submit.prevent="sendFormRequest()">

        <h1>{{ $t("loentraek.titel1") }}</h1>

          <div class="container-fluid">
            <div class="row">
              <div class="col-4">
                <s-field name="ger_nr"
                         :label="$t('loentraek.ger_nr')"
                         type="text"
                         required
                         v-model="ger_nr"/>
              </div>
            </div>
            <div class="row">
              <div class="col-3">
                <!--TODO: Change to https://www.npmjs.com/package/vue-monthly-picker or https://github.com/charliekassel/vuejs-datepicker-->
                <s-field name="traekmaaned"
                         :label="$t('loentraek.traekmaaned')"
                         type="month"
                         required
                         v-model="traekmaaned"
                />
              </div>
            </div>
            <div class="row">
              <div class="col-4">
                <s-field name="loentraek"
                         :label="$t('loentraek.loentraek')"
                         type="text"
                         required v-model="loentraek"
                />
              </div>
            </div>
          </div>

            <div class="row">
              <div class="col">
                <button @click.prevent="navigateTo('/loentraeksindberetning/indberet_pr_cpr')">
                  {{ $t('loentraek.fordel_pr_cpr') }}
                </button>
                <button type="submit"
                        @click="isSubmitted = true">
                  {{ $t('common.indberet') }}
                </button>
              </div>
            </div>

        </form>

    </article>

</template>

<script>
import axios from 'axios'
// The file fordringsgruppe.js below is generated by the command `make frontend`
import { notify } from '../utils/notify/Notifier.js'

export default {
  data: function () {
    return {
      ger_nr: null,
      traekmaaned: null,
      loentraek: null,
      csrftoken: null,
      isSubmitted: false
    }
  },
  computed: {

  },
  methods: {
    navigateTo: function (nav) {
      this.$router.push({
        path: nav
      })
    },
    getCSRFToken: function () {
      this.csrftoken = document.cookie.replace(
        /(?:(?:^|.*;\s*)csrftoken\s*=\s*([^;]*).*$)|^.*$/,
        '$1'
      )
    },
    getFileData: function (files) {
      this.fil = files[0]
    },
    // fetchFormData: function () {
    //   let formdata = new FormData()
    //   let that = this
    //   function appendData (string) {
    //     if (that[string] !== null) {
    //       formdata.append(string, that[string])
    //     }
    //   }
    //   this.form_fields.forEach(appendData)
    //   return formdata
    // },
    sendFormRequest: function () {
      // let formdata = this.fetchFormData()
      let formdata = new FormData()
      formdata.append(this.ger_nr)
      formdata.append(this.traekmaaned)
      formdata.append(this.loentraek)
      axios({
        url: '/inkassosag',
        data: formdata,
        method: 'post',
        headers: {
          'X-CSRFToken': this.csrftoken,
          'X-AKA-BRUGER': 'Unknown'
        }
      })
        .then(res => {
          notify('The server has responded and it was happy!')
          console.log('Server response!')
          console.log(res)
        })
        .catch(err => {
          console.log('there was an error')
          console.log(err.message)
        })
    }
  },
  created: function () {
    this.getCSRFToken()
    notify(`Welcome to this page. ${this.$t('title')}`)
  }
}
</script>

<style scoped>

</style>
