# Develop playbook.
#
# Should configure a development setup to the point where a server or
# equivalent can be started with a single command.
#
# After `vagrant ssh`, run `cd /vagrant` and then `make` to run everything
#

---

- import_playbook: default.yml


- hosts: all

  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root

  pre_tasks:
      - name: Install flake8
        apt:
          name: flake8

  
  post_tasks:
    - name: Install Node Requirements
      npm:
        path: "{{ npm_path }}"
    - name: Install Python Dev Requirements
      pip: 
        requirements: /vagrant/backend/doc/dev-requirements.txt
        executable: pip3
  
  vars:
    npm_path: /vagrant/frontend

  roles:
  - sphinx
  - vue
...
