---
- name: Build release tarball with both backend and frontend
  become: no
  local_action: command tar cfz /tmp/backend.tar.gz --exclude='*.pyc' --exclude='local_settings.py' --exclude='.gitignore' ../../backend ../../shared

- name: ensure project dir exists
  file:
    path: "{{project_dir}}"
    state: directory

- name: unpack release
  unarchive:
    src: /tmp/backend.tar.gz
    dest: "{{project_dir}}"
    remote_src: no
