<template>

  <article class="indberet_fordring" :key="fordring" v-if="!submittedSuccessfully">
    <form @submit.prevent="sendFormRequest()" :class="{submitted: isSubmitted}">
      <h1>{{ $t('inkasso.title') }}</h1>
      <div class="container-fluid">
        <div class="row">
          <div class="col-4">
            <a href="/static/csv/Fordring.csv">{{ $t('inkasso.template') }}</a>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <input type="file" name="file" @change="setFileData($event.target.files)">
          </div>
        </div>
        <div class="row">
          <div class="col-2">
            <input type="submit" :value="$t('common.gem')" @click="isSubmitted = true">
          </div>
        </div>
      </div>
    </form>
  </article>

  <article class="success" v-else>
    <form>
      <h1>{{ $t('inkasso.success') }}</h1>
      <div class="container-fluid">
        <div class="row">
          <div class="col-4">
            <div v-if="fordringsnumre.length === 1" :key="fordringsnumre">
              {{ $t('inkasso.nummervisning', { 'nummer': fordringsnumre[0] }) }}
            </div>
            <div v-else>
              {{ $t('inkasso.nummervisning_pl') }}
              <ul>
                <li v-for="n in fordringsnumre" :key="fordringsnumre">
                  {{ n }}
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <button @click="reload()">{{ $t('inkasso.reload') }}</button>
            <router-link to="/" tag="button">{{ $t('common.forside') }}</router-link>
          </div>
        </div>
      </div>
    </form>
  </article>

</template>

<script>
    import axios from 'axios'
    // The file fordringsgruppe.js below is generated by the command `make frontend`

    export default {
        data: function() {
            return {
                fordring: 1,
                fordringsnumre: [],
                csv_data: null,
                csrftoken: null,
                isSubmitted: false,
                submittedSuccessfully: false
            }
        },
        methods: {
            getCSRFToken: function() {
                this.csrftoken = document.cookie.replace(/(?:(?:^|.*;\s*)csrftoken\s*\=\s*([^;]*).*$)|^.*$/, "$1");
            },
            setFileData: function(files) {
                this.files = files;
            },
            sendFormRequest: function() {
                let data = new FormData();
                data.append("file", this.files[0]);
                axios({
                    url: '/inkassosag/upload',
                    data: data,
                    method: 'post',
                    headers: {
                        'X-CSRFToken': this.csrftoken,
                        'X-AKA-BRUGER': 'Unknown'
                    },
                })
                .then(res => {
                    this.fordringsnumre = [];
                    for (let i=0; i<res.data.length; i++) {
                        let d = res.data[i];
                        this.fordringsnumre.push(d['rec_id'] || d['response']['rec_id']);
                    }
                    this.submittedSuccessfully = true;
                })
                .catch(error => {
                    notifyError(error, localStorage.getItem('language') || 'kl', this._i18n);
                });
            },
            reload: function () {
                this.fordringsnumre = null;
                this.fordring += 1;
                this.submittedSuccessfully = false;
            }
        },
        created: function () {
            this.getCSRFToken();
        }
    }
</script>

<style scoped>
    tr {
        border-bottom: 1px solid #ddd;
    }
</style>
