<template>

  <article class="indberet_fordring" :key="fordring" v-if="!submittedSuccessfully">
    <form @submit.prevent="sendFormRequest()" :class="{submitted: isSubmitted}">
      <h1>{{ $t('inkasso.title') }}</h1>
      <div class="container-fluid">
        <div class="row">
          <div class="col-4">
            <input type="file" name="file" @change="setFileData($event.target.files)">
          </div>
        </div>
        <div class="row">
          <div class="col-2">
            <input type="submit" :value="$t('common.gem')" @click="isSubmitted = true">
          </div>
        </div>
      </div>
    </form>
  </article>

  <article class="success" v-else>
    <form>
      <h1>{{ $t('inkasso.success') }}</h1>
      <div class="container-fluid">
        <div class="row">
          <div class="col-4">
            {{ $t('inkasso.nummervisning', { 'nummer': fordringsnummer }) }}
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <button @click="reload()">{{ $t('inkasso.reload') }}</button>
            <router-link to="/" tag="button">{{ $t('common.forside') }}</router-link>
          </div>
        </div>
      </div>
    </form>
  </article>

</template>

<script>
    import axios from 'axios'
    // The file fordringsgruppe.js below is generated by the command `make frontend`
    import {groups} from '@/assets/fordringsgruppe'
    import {notify, notifyError} from '../utils/notify/Notifier.js'
    import formValid from '@/mixins/formValid'

    export default {
        data: function() {
            return {
                csv_data: null,
                csrftoken: null
            }
        },
        methods: {
            getCSRFToken: function() {
                this.csrftoken = document.cookie.replace(/(?:(?:^|.*;\s*)csrftoken\s*\=\s*([^;]*).*$)|^.*$/, "$1");
            },
            setFileData: function(files) {
                this.files = files;
            },
            sendFormRequest: function() {
                let data = new FormData();
                data.append("file", this.files[0]);
                axios({
                    url: '/inkassosag/upload',
                    data: data,
                    method: 'post',
                    headers: {
                        'X-CSRFToken': this.csrftoken,
                        'X-AKA-BRUGER': 'Unknown'
                    },
                })
                .then(res => {
                    console.log('Server response!')
                    console.log(res)
                })
                .catch(err => {
                    console.log('there was an error')
                    console.log(err.message)
                })
            },
            reload: function () {
                this.form_fields.forEach(name => {
                    this[name] = null;
                });
                this.files = [];
                this.fordringsnummer = null;
                this.fordring += 1;
                this.submittedSuccessfully = false;
            }
        },
        created: function () {
            this.getCSRFToken();
        }
    }
</script>

<style scoped>
    tr {
        border-bottom: 1px solid #ddd;
    }
    .dropdown {
        border: 1px solid #EAECEE;
    }
    textarea {
        resize: none;
    }
</style>
